version: "3.8"

services:
  frontend:
    image: ${DOCKER_USERNAME}/todo-frontend:latest
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - todo-network

  backend:
    image: ${DOCKER_USERNAME}/todo-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/todos
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=todos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - todo-network

networks:
  todo-network:
    driver: overlay

volumes:
  postgres_data:
